# _config.yml — trimmed & tidy
locale          : "en-UK"
title           : "Mehrad Haghshenas"
title_separator : "-"
name            : "Mehrad Haghshenas"
description     : "PhD student in Computer Science at the University of Waterloo"
url             : "https://mehrad31415.github.io"
baseurl         : ""          # root of the repository
repository      : "mehrad31415/mehrad31415.github.io"
timezone        : "America/Toronto"

# Theme + plugins
theme           : "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jemoji
  # jekyll-sitemap REMOVED per request

# Author box
author:
  avatar   : "profile.png"
  name     : "Mehrad"
  bio      : "CS PhD @ UWaterloo"
  email    : "m3haghsh@uwaterloo.ca"
  github   : "mehrad31415"
  stackoverflow: "19961014/runtimeerror31415"
  location : "Canada"

# Reading/build options
future            : false           # hide “Future Blog Post”
permalink         : /:categories/:title/
markdown          : kramdown
highlighter       : rouge

# Collections you actually use
collections:
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
